export interface ExpertAnalysis {
  expertName: string;
  analysis: string;
}

export interface NudgeReport {
  url: string;
  pageTitle: string;
  generatedAt: string;
  expertAnalyses: ExpertAnalysis[];
  executiveSummary: string;
}

export function generateReportHtml(report: NudgeReport): string {
  const expertSections = report.expertAnalyses
    .map(
      (ea) => `
      <div style="margin-bottom: 32px; padding: 24px; background: #f9fafb; border-radius: 12px; border-left: 4px solid #6366f1;">
        <h2 style="margin: 0 0 16px 0; color: #1f2937; font-size: 20px;">${ea.expertName}</h2>
        <div style="color: #374151; line-height: 1.7; white-space: pre-wrap;">${ea.analysis}</div>
      </div>
    `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Nudge Panel Report — ${report.pageTitle}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #ffffff;
      color: #1f2937;
    }
    .header {
      text-align: center;
      margin-bottom: 48px;
      padding-bottom: 32px;
      border-bottom: 2px solid #e5e7eb;
    }
    .header h1 {
      font-size: 28px;
      color: #111827;
      margin-bottom: 8px;
    }
    .header .url {
      color: #6366f1;
      font-size: 14px;
      word-break: break-all;
    }
    .header .date {
      color: #9ca3af;
      font-size: 13px;
      margin-top: 8px;
    }
    .summary {
      background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
      color: white;
      padding: 32px;
      border-radius: 12px;
      margin-bottom: 40px;
    }
    .summary h2 {
      margin: 0 0 16px 0;
      font-size: 22px;
    }
    .summary .content {
      line-height: 1.7;
      white-space: pre-wrap;
    }
    .footer {
      text-align: center;
      margin-top: 48px;
      padding-top: 24px;
      border-top: 2px solid #e5e7eb;
      color: #9ca3af;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Nudge Panel Report</h1>
    <div class="url">${report.url}</div>
    <div class="date">Generated ${report.generatedAt}</div>
  </div>

  <div class="summary">
    <h2>Executive Summary</h2>
    <div class="content">${report.executiveSummary}</div>
  </div>

  ${expertSections}

  <div class="footer">
    <p>This report was generated by the Nudge Panel — a panel of AI experts analysing your landing page.</p>
    <p>Want the full breakdown with actionable solutions? Get in touch.</p>
  </div>
</body>
</html>`;
}
