import { marked } from "marked";

export interface ExpertAnalysis {
  expertName: string;
  analysis: string;
}

export interface NudgeReport {
  url: string;
  pageTitle: string;
  generatedAt: string;
  expertAnalyses: ExpertAnalysis[];
  executiveSummary: string;
}

function renderMarkdown(md: string): string {
  return marked.parse(md, { async: false }) as string;
}

export function generateReportHtml(report: NudgeReport): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="color-scheme" content="light dark" />
  <meta name="supported-color-schemes" content="light dark" />
  <title>Nudge Panel Report — ${report.pageTitle}</title>
  <style>
    :root {
      color-scheme: light dark;
      supported-color-schemes: light dark;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      background-color: #ffffff;
      color: #1f2937;
    }
    .md h1, .md h2, .md h3, .md h4 { color: #1f2937; margin-top: 20px; margin-bottom: 8px; }
    .md p { margin: 0 0 12px 0; }
    .md ul, .md ol { margin: 0 0 12px 0; padding-left: 24px; }
    .md li { margin-bottom: 4px; }
    .md strong { font-weight: 700; }
    .md em { font-style: italic; }
    .md code { background-color: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
    .md blockquote { border-left: 3px solid #6366f1; margin: 0 0 12px 0; padding: 8px 16px; color: #6b7280; }
    .md hr { border: none; border-top: 1px solid #e5e7eb; margin: 16px 0; }
    .md table { border-collapse: collapse; width: 100%; margin-bottom: 12px; }
    .md th, .md td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }
    .md th { background-color: #f3f4f6; font-weight: 600; }
    @media (prefers-color-scheme: dark) {
      body {
        background-color: #111827 !important;
        color: #e5e7eb !important;
      }
      .header h1 {
        color: #f9fafb !important;
      }
      .header .url {
        color: #818cf8 !important;
      }
      .header .date {
        color: #9ca3af !important;
      }
      .header .border-line {
        border-bottom-color: #374151 !important;
      }
      .expert-section {
        background-color: #1f2937 !important;
        border-left-color: #818cf8 !important;
      }
      .expert-section h2 {
        color: #f9fafb !important;
      }
      .expert-section .md {
        color: #d1d5db !important;
      }
      .md h1, .md h2, .md h3, .md h4 {
        color: #f9fafb !important;
      }
      .md code {
        background-color: #374151 !important;
        color: #e5e7eb !important;
      }
      .md blockquote {
        border-left-color: #818cf8 !important;
        color: #9ca3af !important;
      }
      .md hr {
        border-top-color: #374151 !important;
      }
      .md th, .md td {
        border-color: #374151 !important;
      }
      .md th {
        background-color: #1f2937 !important;
        color: #e5e7eb !important;
      }
      .footer {
        border-top-color: #374151 !important;
        color: #9ca3af !important;
      }
    }
  </style>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; background-color: #ffffff; color: #1f2937;">
  <div class="header" style="text-align: center; margin-bottom: 48px; padding-bottom: 32px;">
    <div class="border-line" style="border-bottom: 2px solid #e5e7eb; padding-bottom: 32px;">
      <h1 style="font-size: 28px; color: #111827; margin-bottom: 8px;">Nudge Panel Report</h1>
      <div class="url" style="color: #6366f1; font-size: 14px; word-break: break-all;">${report.url}</div>
      <div class="date" style="color: #9ca3af; font-size: 13px; margin-top: 8px;">Generated ${report.generatedAt}</div>
    </div>
  </div>

  <div class="summary" style="background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color: #ffffff; padding: 32px; border-radius: 12px; margin-bottom: 40px;">
    <h2 style="margin: 0 0 16px 0; font-size: 22px; color: #ffffff;">Executive Summary</h2>
    <div class="md" style="line-height: 1.7; color: #ffffff;">${renderMarkdown(report.executiveSummary)}</div>
  </div>

  ${report.expertAnalyses
    .map(
      (ea) => `
  <div class="expert-section" style="margin-bottom: 32px; padding: 24px; background-color: #f9fafb; border-radius: 12px; border-left: 4px solid #6366f1;">
    <h2 style="margin: 0 0 16px 0; color: #1f2937; font-size: 20px;">${ea.expertName}</h2>
    <div class="md" style="color: #374151; line-height: 1.7;">${renderMarkdown(ea.analysis)}</div>
  </div>`
    )
    .join("")}

  <div class="footer" style="text-align: center; margin-top: 48px; padding-top: 24px; border-top: 2px solid #e5e7eb; color: #9ca3af; font-size: 13px;">
    <p>This report was generated by the Nudge Panel — a panel of AI experts analysing your landing page.</p>
    <p>Want the full breakdown with actionable solutions? Get in touch.</p>
  </div>
</body>
</html>`;
}
