import resend from "@/lib/worker/models/resend";

async function sendTeaserEmail(to: string, jobId: string, pageTitle: string, executiveSummaryExcerpt: string): Promise<{ id: string }> {
  const baseUrl = process.env.BASE_URL || "https://nudgepanel.com";
  const reportUrl = `${baseUrl}/report/${jobId}`;

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Your Nudge Panel Report is Ready</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; background-color: #ffffff; color: #1f2937;">
  <div style="text-align: center; margin-bottom: 32px;">
    <h1 style="font-size: 24px; color: #111827; margin-bottom: 8px;">Your Nudge Panel Report is Ready</h1>
    <p style="color: #6b7280; font-size: 14px;">Analysis of <strong>${pageTitle}</strong></p>
  </div>

  <div style="background-color: #f9fafb; border-radius: 12px; padding: 24px; margin-bottom: 32px; border-left: 4px solid #6366f1;">
    <p style="color: #374151; line-height: 1.7; margin: 0;">${executiveSummaryExcerpt}</p>
  </div>

  <div style="text-align: center; margin-bottom: 32px;">
    <a href="${reportUrl}" style="display: inline-block; background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color: #ffffff; text-decoration: none; padding: 16px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">View Your Full Report</a>
  </div>

  <div style="text-align: center; color: #9ca3af; font-size: 13px; border-top: 1px solid #e5e7eb; padding-top: 24px;">
    <p>This report was generated by the Nudge Panel — a panel of AI experts analysing your landing page.</p>
  </div>
</body>
</html>`;

  const { data, error } = await resend.emails.send({
    from: "Nudge Panel Experts <noreply@agentbloom.io>",
    to,
    subject: `Your Nudge Panel Report is Ready: ${pageTitle}`,
    html,
  });

  if (error) {
    throw new Error(`Failed to send teaser email: ${error.message}`);
  }

  return data!;
}

export default sendTeaserEmail;
