import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";

function AiDisclaimer(): React.ReactElement {
  return (
    <Box sx={{ mb: 6, p: 3, bgcolor: "grey.100", borderRadius: 2, display: "flex", gap: 2, alignItems: "flex-start" }}>
      <InfoOutlinedIcon sx={{ color: "text.secondary", mt: 0.25 }} />
      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 600, mb: 0.5 }}>
          A note on AI analysis
        </Typography>
        <Typography variant="body2" sx={{ color: "text.secondary", lineHeight: 1.7 }}>
          This report was generated by AI. AI analysis is powerful but imperfect — it spots patterns humans miss, but lacks the nuance of a real conversation. Think of this as a starting point, not a final verdict. For the full picture, talk to a human.
        </Typography>
      </Box>
    </Box>
  );
}

export default AiDisclaimer;
